### ISSUE TITLE
Ability to rebind ctrl part of narrator keybind

### ISSUE THREAD

**Issue by muzikbike** [quat1024/RebindNarrator#3]
Currently, the only part of the narrator keybind that can be configured is the b at the end. This is fine for people who want the narrator out of the way, but forbids assigning it to a single key without ctrl.
![2022-06-24_07 55 59](https://user-images.githubusercontent.com/52297970/175488555-8a9cb2db-111b-4b2f-9cd0-1f3140cea65a.png)

RandomPatches (still stuck in 1.16.5) allows for the key to either be bound to a single key or a ctrl combo:
![2022-06-24_08 39 58](https://user-images.githubusercontent.com/52297970/175488679-f7a73560-4e00-4a91-9f07-94c00a5c4f1c.png)

I'm not sure if making key combos bindable alongside single key presses would bloat the mod or go outwith its scope (especially if any control can be made into a combo rather than just the narrator key), but it's something I'd like to see nonetheless if it can be done, as there seems to be no sign of a new RandomPatches update.

**Comment by quat1024** [comment]
Right, yeah, I was hoping someone wouldn't notice 😅 I agree that this would be a nice feature to add

The main problem is that ctrl/shift/alt keybinds are [part of Forge, not vanilla minecraft](https://github.com/MinecraftForge/MinecraftForge/blob/7f77d24f459f6f9cb69891ae02f5d864a633e2e9/patches/minecraft/net/minecraft/client/KeyMapping.java.patch), so as a Fabric mod I can't do that. There are projects such as [AMECS](https://www.curseforge.com/minecraft/mc-mods/amecs) that attempt to bring the scheme to Fabric, but ideally I don't want to *require* such a large and fundamental (and kinda-incompatible-with-stuff, apparently?) dependency for this 2kb mod.

It would be nice to gracefully support AMECS, and then make a note on the curseforge page that you can add amecs for fancier keybinds. It sounds like "make the key default to `(amecs CTRL) + B` and also patch out the vanilla check for the ctrl key, if amecs is present" would work.

**Comment by quat1024** [comment]
Oh, well, would you look at that, right from randompatches buildscript
```gradle
dependencies {
	modImplementation "de.siphalor:amecsapi-1.16:1.1.1+mc1.16-rc1"
```
Apparently randompatches also uses AMECS 🤷 I didn't know there was a fabric version of randompatches at all

**Comment by quat1024** [comment]
Fiiinally got around to this mod. Ok, I made a separate implementation that takes AMECS' concepts of key modifiers into account. It determines which one to use at startup, if AMECS is loaded it will use the amecs one, else it will fall back on an impl for NMUK (amecs dep that allows you to set multiple keybindings for the same thing, needed special casing on my end too) and if that's missing too it will use the regular vanilla one.

Dunno why I didn't think to do that
